### ISSUE TITLE
Add tag for spell school

### ISSUE THREAD

**Issue by nickcoutsos** [ephe/grimoire#133]
Do you think it would be feasible to tag each spell with its associated school of magic? I wrote a crappy script in Python to update each of the posts but then realized that this might not really work for filtering by multiple tags.

Is it something you had considered? I guess my use case would be finding enchantment/illusion spells for an arcane trickster rogue, so maybe other classes wouldn't be as interested.

**Comment by ephe** [comment]
Definitely can tag each spell with a school of magic (though I'll have some yaml work on my side); less sure how to filter by multiple tags at once. You're certainly welcome to add the tags in if your script, but the rest of the implementation I'll have to mull over...

**Comment by nickcoutsos** [comment]
I might have a go at that today as well. I was thinking of rendering another bar below the classes showing each of the schools and tying javascript to that to filter (or perhaps grey out) spells from unselected schools.

**Comment by ephe** [comment]
Closing this, and opening another issue to refine this behavior in the future...
