### ISSUE TITLE
So, I hope this is okay...

### ISSUE THREAD

**Issue by chisaipete** [ephe/grimoire#153]
I copied your current build and modified it and imported most of the SRD monsters into it to create a Monster Manual...I hope that is okay :)

https://github.com/chisaipete/bestiary

**Comment by jayrab** [comment]
From a gm prospective its really nice to see this, though I think your bestiary types are broken.

**Comment by Socratov** [comment]
@jayrab form a Druid/Sorcerer/Warlock/Wizard (and any other class that can summon elementals, woodland beings, animals, demons, etc., or cast/transform into another being) perspective as well.

**Comment by chisaipete** [comment]
I thought so too, for quick Stat block lookup...and maybe a place to put community built custom baddies.  @jayrab I believe some of the types are broken because some tags are missing from creatures.  I think @Socratov opened an issue on the repo for this, right?  Of course, I want to make sure that my blatant copying of the work by @ephe is okay with them before working too much on it.

**Comment by chisaipete** [comment]
@jayrab @Socratov The tag issue is now fixed and your issue is closed on the bestiary :smile:

**Comment by ephe** [comment]
@chisaipete I think it's awesome and I'm glad you could make use of the code. Have fun!
