### ISSUE TITLE
Logins and saved spellbooks?

### ISSUE THREAD

**Issue by haltingpoint** [ephe/grimoire#175]
Would love some sort of oauth-based login that would let me create and access spellbooks for my individual characters.  I run a Pact of the Tome warlock, so as I get lots of spells, particularly from other classes, being able to save those all under a book and have them pre-filtered into a list would be super useful so I don't need to search for the spell every time.

**Comment by thebombzen** [comment]
Github Pages is a static CDN so there's no server-side programming, so it wouldn't be possible unless you host it yourself. However, as a tome warlock, tag search would be the most useful feature.

If you check out [my fork](http://thebombzen.github.io/grimoire/) you can search with tags like [warlock | warlock (fae) | cantrip | level1 & ritual](https://thebombzen.github.io/grimoire/?tagSearch=warlock+%7C+warlock+%28fae%29+%7C+cantrip+%7C+level1+%26+ritual).

I was gonna pull in the "search by tag" but a lot of people already did that.

**Comment by ephe** [comment]
As @thebombzen said, this was built only as a static reference, though theoretically this could be used as a reference for another tool since the spells are hosted on static pages.

Closing this issue in any case.
