### ISSUE TITLE
Recently Viewed Spells?

### ISSUE THREAD

**Issue by haltingpoint** [ephe/grimoire#176]
Would love some persistent nav element that shows the last 5 or so recently viewed (not searched) spells. If I'm frequently jumping between a few spells, so that lets me have them at my fingertips.

**Comment by ephe** [comment]
May look into this at some point, but it's not a priority at the moment vs some other features that have been sitting on the backburner. Right now browser history or bookmarking (since the spells are all static pages) might serve your purpose?

**Comment by ephe** [comment]
Aaaaalso Github only allows hosting static pages so I'm not even sure I could do it here!
