### ISSUE TITLE
Bestow Curse

### ISSUE THREAD

**Issue by ephe** [ephe/grimoire#34]
Formatting check:
* check bullet points
* maybe italicize 'remove curse'?
* bold 'At Higher Levels.'

**Comment by zetsevs** [comment]
Question what do you mean check bullet points also how do I italicize with this in the text editor and I must of glance over at higher levels part Ive been focusing more on catching those now

**Comment by ephe** [comment]
When I say I need to check bullet points, I mean I need to check whether real bullet point characters work, or whether Markdown wants an asterisk instead.

For italics, put one asterisk at the start and end of what you want to italicize. To bold, you use two asterisks instead of one.

And all good! These issues are mostly reminders to myself to check or fix things before I run the conversion script.
