### ISSUE TITLE
Arcane lock

### ISSUE THREAD

**Issue by ephe** [ephe/grimoire#79]
* Fix line break issue.

**Comment by jayrab** [comment]
what was the line break issue?

**Comment by ephe** [comment]
Oh, looking at it again, actually a few issues:
* line break in the components
* range "touch" should be capitalized
* "Abjuration" should be lowercase

**Comment by jayrab** [comment]
all the spells that have been submitted by my team likely all have the spell type with the first letter capped.

**Comment by ephe** [comment]
Fixed.
