### ISSUE TITLE
Fire Bolt

### ISSUE THREAD

**Issue by Slam2304** [ephe/grimoire#81]
The Fire Bolt cantrip has the same description as the Dancing Lights cantrip.
![wpgmevp 1](https://cloud.githubusercontent.com/assets/3155965/5609066/1a48c684-947d-11e4-98bd-ae63dd917cb5.png)
![uuzhqbw 1](https://cloud.githubusercontent.com/assets/3155965/5609068/299c8594-947d-11e4-980b-29bbbdc05312.png)

**Comment by jayrab** [comment]
made the edit, just waiting for approval for it to change over, thank you for your help.

**Comment by ephe** [comment]
Just merged in the change, thanks folks!
