### ISSUE TITLE
Firebolt issue in the compiled website

### ISSUE THREAD

**Issue by kusuri8** [ephe/grimoire#99]
On the compiled website (http://ephe.github.io/grimoire/), details for the sorcerer cantrip Fire Bolt is accidentally the same as dancing lights. It looks like that's been fixed in the _posts file here, but not in the compiled version. 

Is this still live? Will it be compiled soon? What can I do to help? Thanks!

**Comment by ephe** [comment]
Hi! The project's been somewhat dormant since my D&D group broke up, but I
do have a batch of files sitting on my laptop still waiting to be compiled
so I'll see if I can't do that sometime soon, at least.

**Comment by ephe** [comment]
Fixed, thanks for reporting this @kusuri8!
